# Copyright[2017]<Chaoyi Yang> [legalcpoyright]
# Name: Chaoyi Yang
# Student ID: 1465947
# UW Email: yangc22@uw.edu

CXX = g++
SOURCES = socketuse.cc ex15.cc

all: ex15

ex15: $(SOURCES)
	$(CXX) -g -Wall -std=c++11 -o $@ $^

clean:
	rm -rf *~ *.o ex15
